@baseUrl = http://localhost:3000/api/v1

### 1. Crear un usuario (POST)
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Bastian",
  "email": "bastian1@example.com",
  "password": "securepassword123"
}

### 2. Obtener un usuario por ID (GET)
# Copia y pega el ID (UUID) devuelto en la creación de arriba
@userId = ee4d02f3-d711-47de-b7aa-b8b1f233f938

GET {{baseUrl}}/users/{{userId}}

### 3. Actualizar un usuario (PATCH)
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "Bastian Actualizado",
  "email": "bastian.nuevo@example.com"
}

### 4. Eliminar/Desactivar un usuario (DELETE)
DELETE {{baseUrl}}/users/{{userId}}
